name: Actions CI

on:
  push:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: build-push
      env:
        DOCKER_HUB_USER: ${{ secrets.DOCKER_HUB_USER }}
        DOCKER_HUB_KEY: ${{ secrets.DOCKER_HUB_KEY }}
        DOCKER_HUB_REPO: dnastacio
      run: |
        echo 'Docker Login...'
        docker login -u ${DOCKER_HUB_USER} -p ${DOCKER_HUB_KEY}
        echo 'Running build and pushing to docker registry...'
        docker build --tag ${DOCKER_HUB_REPO}/github-board-sync:latest
